---
- name: install packages
  ansible.builtin.yum: name={{ item }} state=present
  with_items:
    - opendkim
  tags:
    - yum

- name: instanciate config
  ansible.builtin.template: src=opendkim/opendkim.conf dest=/etc/opendkim.conf
  notify:
    - restart opendkim

- name: instanciate tables
  ansible.builtin.template: src=opendkim/{{ item }} dest=/etc/opendkim/
  with_items:
    - SigningTable
    - KeyTable
  notify:
    - restart opendkim

- name: enable and start opendkim
  ansible.builtin.service: name=opendkim enabled=yes state=started
