---
- name: install packages
  yum: name={{ item }} state=latest
  with_items:
    - opendkim
  tags:
    - opendkim
    - yum

- name: instanciate config
  template: src=opendkim/opendkim.conf dest=/etc/opendkim.conf
  tags:
    - opendkim
  notify:
    - restart opendkim

- name: instanciate tables
  template: src=opendkim/{{ item }} dest=/etc/opendkim/
  with_items:
    - SigningTable
    - KeyTable
  tags:
    - opendkim
  notify:
    - restart opendkim

- name: enable and start opendkim
  service: name=opendkim enabled=yes state=started
  tags:
    - opendkim
