---
# - name: set hostname
#   command: hostnamectl --static set-hostname {{ inventory_hostname }}


- name: install packages via yum
  yum: name=postfix state=latest
  when: "ansible_distribution in ['Fedora']"
  tags:
    - yum

- name: install packages via apt
  apt: name=postfix state=latest
  when: "ansible_distribution in ['Ubuntu', 'Debian']"
  tags:
    - apt

- name: instanciate config files
  template: dest=/etc/postfix/{{ item }} src=postfix/{{ item }} lstrip_blocks=yes
  with_items:
    - master.cf
    - main.cf
  notify:
    - restart postfix

- name: generate additional config files
  template: src=postfix/config
            dest=/etc/postfix/{{ item.name }}
            mode=0600
            owner=root
            group=root
  with_items: "{{ mta_config_files }}"
  notify:
    - restart postfix

- name: create policy and access database directories
  file: path="/etc/postfix/{{ item }}"
        state=directory
        mode=0775
        owner=root
        group=root
  with_items:
    - access.d
    - policy.d
    - policy.d/client_restrictions
    - policy.d/sender_restrictions
    - policy.d/relay_restrictions
    - policy.d/recipient_restrictions

- name: update access databases
  template: src=postfix/access
            dest={{ item.key }}
            mode="{{ item.mode | default('0664') }}"
            owner={{ item.owner | default("root") }}
            group={{ item.group | default("root") }}
  with_dict: "{{ mta_access_databases }}"
  register: access_database_update

- name: compile access databases
  command: postmap "{{ '%s:%s'|format(item.item.value.type, item.item.key) }}"
  when: item is changed
  with_items: "{{ access_database_update.results | default([]) }}"
  notify:
    - reload postfix

- name: update alias tables
  template: src=postfix/aliases
            dest={{ item.file }}
            mode="{{ item.mode | default('0664') }}"
            owner={{ item.owner | default("root") }}
            group={{ item.group | default("root") }}
  with_items: "{{ mta_alias_database }}"
  tags:
    - postfix_virtual_map
  register: alias_map_update

- name: compile alias tables
  command: postalias "{{ '%s:%s'|format(item.item.type, item.item.file) }}"
  when: item is changed
  with_items: "{{ alias_map_update.results | default([]) }}"
  notify:
    - reload postfix
  tags:
    - postfix_virtual_map

- name: update virtual tables
  template: src=postfix/virtual dest=/etc/postfix/virtual_{{ item.domain }}
  when: item is mapping
  with_items: "{{ mta_virtual_maps | default(omit) }}"
  tags:
    - postfix_virtual_map
  register: virtual_map_update

- name: compile virtual tables
  command: postmap /etc/postfix/virtual_{{ item.item.domain }}
  when: item is changed
  with_items: "{{ virtual_map_update.results | default([]) }}"
  notify:
    - reload postfix
  tags:
    - postfix_virtual_map

- name: create alias include dir
  file: path=/etc/postfix/aliases.d/ state=directory

- name: create placeholder file
  copy: dest=/etc/postfix/aliases.d/placeholder.aliases content=""

- name: force alias includer generation at this point
  command: /bin/true
  notify:
    - update include alias file

- name: update transport map
  template: src=postfix/transport_map dest=/etc/postfix/transports
  when: mta_transport_map is mapping
  tags:
    - postfix_transport_map
  register: postfix_transport_map

- name: compile transport map
  command: postmap /etc/postfix/transports
  when: postfix_transport_map is changed
  tags:
    - postfix_transport_map

- name: deploy sasl password map for relaying
  template: src=postfix/password_map
            dest="{{ mta_relayhost_auth.mapfile }}"
  when: mta_relayhost and mta_relayhost_auth
  register: password_map
  notify:
    - reload postfix

- name: compile sasl password map for relaying
  command: postmap "{{ mta_relayhost_auth.mapfile }}"
  when: password_map is changed
  notify:
    - reload postfix

- name: upload certificate
  copy: content="{{ mta_tls_cert }}"
        dest=/etc/postfix/ssl.crt
        owner=root
        group=root
        mode=0444
  when: mta_tls_cert | default(False)
  notify:
  - reload postfix
  tags:
  - certificate

- name: upload key
  copy: content="{{ mta_tls_key }}"
        dest=/etc/postfix/ssl.key
        owner=root
        group=root
        mode=0400
  when: mta_tls_key | default(False)
  notify:
  - reload postfix
  tags:
  - certificate
  - requires-secret

- name: setup core firewall service files
  copy: src=firewalld/{{ item }}.xml dest=/etc/firewalld/services/
  with_items:
    - smtpd
  when: ansible_distribution in ['Fedora']
  register: firewall_rule_copy1
  tags:
    - firewall

- name: setup submission firewall service files
  copy: src=firewalld/{{ item }}.xml dest=/etc/firewalld/services/
  when: mta_msa and ansible_distribution in ['Fedora']
  with_items:
    - submission
  register: firewall_rule_copy2
  tags:
    - firewall

- name: reload firewall
  command: firewall-cmd --reload
  when: (firewall_rule_copy1 is changed) or (firewall_rule_copy2 is changed)
  tags:
    - firewall

- name: enable core services in firewall
  command: firewall-cmd --permanent --zone=public --add-service={{ item }}
  when: ansible_distribution in ['Fedora']
  with_items:
    - smtpd
  tags:
    - firewall

- name: enable submission in firewall
  command: firewall-cmd --permanent --zone=public --add-service={{ item }}
  when: mta_msa and ansible_distribution in ['Fedora']
  with_items:
    - submission
  tags:
    - firewall

- name: start and enable postfix
  service: name=postfix state=started enabled=yes
