---
# - name: set hostname
#   command: hostnamectl --static set-hostname {{ inventory_hostname }}


- name: install packages via yum
  yum: name={{ item }} state=latest
  when: "ansible_distribution in ['Fedora']"
  with_items:
    - postfix
  tags:
    - postfix
    - yum

- name: install packages via apt
  apt: name={{ item }} state=latest
  when: "ansible_distribution in ['Ubuntu', 'Debian']"
  with_items:
    - postfix
  tags:
    - postfix
    - apt

- name: instanciate config files
  template: backup=yes dest=/etc/postfix/{{ item }} src=postfix/{{ item }}
  with_items:
    - master.cf
    - main.cf
  tags:
    - postfix
  notify:
    - reload postfix

- name: update virtual tables
  template: src=postfix/virtual dest=/etc/postfix/virtual_{{ item.domain }}
  when: item is mapping
  with_items: mta_virtual_maps
  tags:
    - postfix
    - postfix_virtual_map
  register: virtual_map_update

- name: compiling virtual tables
  command: postmap /etc/postfix/virtual_{{ item.item.domain }}
  when: item | changed
  with_items: virtual_map_update.results
  notify:
    - reload postfix
  tags:
    - postfix
    - postfix_virtual_map

- name: setup core firewall service files
  copy: src=firewalld/{{ item }}.xml dest=/etc/firewalld/services/
  with_items:
    - smtpd
  when: ansible_distribution in ['Fedora']
  register: firewall_rule_copy1
  tags:
    - postfix
    - firewall

- name: setup submission firewall service files
  copy: src=firewalld/{{ item }}.xml dest=/etc/firewalld/services/
  when: mta_msa and ansible_distribution in ['Fedora']
  with_items:
    - submission
  register: firewall_rule_copy2
  tags:
    - postfix
    - firewall

- name: reload firewall
  command: firewall-cmd --reload
  when: (firewall_rule_copy1|changed) or (firewall_rule_copy2|changed)
  tags:
    - postfix
    - firewall

- name: enable core services in firewall
  command: firewall-cmd --permanent --zone=public --add-service={{ item }}
  when: ansible_distribution in ['Fedora']
  with_items:
    - smtpd
  tags:
    - postfix
    - firewall

- name: enable submission in firewall
  command: firewall-cmd --permanent --zone=public --add-service={{ item }}
  when: mta_msa and ansible_distribution in ['Fedora']
  with_items:
    - submission
  tags:
    - postfix
    - firewall

- name: start and enable postfix
  service: name=postfix state=started enabled=yes
  tags:
    - postfix
