---
# - name: set hostname
#   command: hostnamectl --static set-hostname {{ inventory_hostname }}


- name: install packages
  ansible.builtin.package: name=postfix state=present

- name: discover default configuration values
  ansible.builtin.command: postconf -d
  register: _postfix_config_defaults
  changed_when: false
  check_mode: false

- name: register default configuration values
  ansible.builtin.set_fact:
    postfix_config_defaults: "{{ dict(  _postfix_config_defaults.stdout_lines
                                      | map('regex_replace', '^(\\w+ =)$', '\\1 ')
                                      | map('split', ' = ', 1)) }}"

- name: instanciate config files
  ansible.builtin.template: dest=/etc/postfix/{{ item }} src=postfix/{{ item }} lstrip_blocks=yes
  with_items:
    - master.cf
    - main.cf
  notify:
    - restart postfix

- name: generate additional config files
  ansible.builtin.template: src=postfix/config
            dest=/etc/postfix/{{ item.name }}
            mode=0600
            owner=root
            group=root
  with_items: "{{ mta_config_files_all + mta_config_files }}"
  notify:
    - restart postfix

- name: create policy and access database directories
  ansible.builtin.file: path="/etc/postfix/{{ item }}"
        state=directory
        mode=0755
        owner=root
        group=root
  with_items:
    - access.d
    - policy.d
    - policy.d/client_restrictions
    - policy.d/sender_restrictions
    - policy.d/relay_restrictions
    - policy.d/recipient_restrictions

- name: update access databases
  ansible.builtin.template: src=postfix/access
            dest={{ item.key }}
            mode="{{ item.value.mode | default('0664') }}"
            owner={{ item.value.owner | default("root") }}
            group={{ item.value.group | default("root") }}
  with_dict: "{{ mta_access_databases }}"
  register: access_database_update

- name: compile access databases
  ansible.builtin.command: postmap "{{ '%s:%s'|format(item.item.value.type, item.item.key) }}"
  when: item is changed
  with_items: "{{ access_database_update.results | default([]) }}"
  notify:
    - reload postfix

- name: update alias tables
  ansible.builtin.template: src=postfix/aliases
            dest={{ item.file }}
            mode="{{ item.mode | default('0664') }}"
            owner={{ item.owner | default("root") }}
            group={{ item.group | default("root") }}
  with_items: "{{ mta_alias_database }}"
  tags:
    - postfix_virtual_map
  register: alias_map_update

- name: compile alias tables
  ansible.builtin.command: postalias "{{ '%s:%s'|format(item.item.type, item.item.file) }}"
  when: item is changed
  with_items: "{{ alias_map_update.results | default([]) }}"
  notify:
    - reload postfix
  tags:
    - postfix_virtual_map

- name: update virtual tables
  ansible.builtin.template: src=postfix/virtual dest=/etc/postfix/virtual_{{ item.domain }}
  when: item is mapping
  with_items: "{{ mta_virtual_maps | default(omit) }}"
  tags:
    - postfix_virtual_map
  register: virtual_map_update

- name: compile virtual tables
  ansible.builtin.command: postmap /etc/postfix/virtual_{{ item.item.domain }}
  when: item is changed
  with_items: "{{ virtual_map_update.results | default([]) }}"
  notify:
    - reload postfix
  tags:
    - postfix_virtual_map

- name: create alias include dir
  ansible.builtin.file: path=/etc/postfix/aliases.d/ state=directory

- name: create placeholder file
  ansible.builtin.copy: dest=/etc/postfix/aliases.d/placeholder.aliases content=""

- name: force alias includer generation at this point
  ansible.builtin.command: /bin/true
  notify:
    - update include alias file

- name: update transport map
  ansible.builtin.template: src=postfix/transport_map dest=/etc/postfix/transports
  when: mta_transport_map is mapping
  tags:
    - postfix_transport_map
  register: postfix_transport_map

- name: compile transport map
  ansible.builtin.command: postmap /etc/postfix/transports
  when: postfix_transport_map is changed
  tags:
    - postfix_transport_map

- name: deploy sasl password map for relaying
  ansible.builtin.template: src=postfix/password_map
            dest="{{ mta_relayhost_auth_mapfile }}"
  when: mta_relayhost and mta_relayhost_auth_username
  register: password_map
  notify:
    - reload postfix

- name: compile sasl password map for relaying
  ansible.builtin.command: postmap "{{ mta_relayhost_auth_mapfile }}"
  when: password_map is changed
  notify:
    - reload postfix

- name: upload certificate
  ansible.builtin.copy: content="{{ mta_tls_cert }}"
        dest=/etc/postfix/ssl.crt
        owner=root
        group=root
        mode=0444
  when: mta_tls_cert | default(false)
  notify:
    - reload postfix
  tags:
    - certificate

- name: upload key
  ansible.builtin.copy: content="{{ mta_tls_key }}"
        dest=/etc/postfix/ssl.key
        owner=root
        group=root
        mode=0400
  when: mta_tls_key | default(false)
  notify:
    - reload postfix
  tags:
    - certificate
    - requires-secret

- name: setup core firewall service files
  ansible.builtin.copy: src=firewalld/{{ item }}.xml dest=/etc/firewalld/services/
  with_items:
    - smtpd
  when: ansible_distribution in ['Fedora']
  register: firewall_rule_copy1
  tags:
    - firewall

- name: setup submission firewall service files
  ansible.builtin.copy: src=firewalld/{{ item }}.xml dest=/etc/firewalld/services/
  when: mta_msa and ansible_distribution in ['Fedora']
  with_items:
    - submission
  register: firewall_rule_copy2
  tags:
    - firewall

- name: reload firewall
  ansible.builtin.command: firewall-cmd --reload
  when: (firewall_rule_copy1 is changed) or (firewall_rule_copy2 is changed)
  tags:
    - firewall

- name: enable core services in firewall
  ansible.builtin.command: firewall-cmd --permanent --zone=public --add-service={{ item }}
  when: ansible_distribution in ['Fedora']
  with_items:
    - smtpd
  tags:
    - firewall

- name: enable submission in firewall
  ansible.builtin.command: firewall-cmd --permanent --zone=public --add-service={{ item }}
  when: mta_msa and ansible_distribution in ['Fedora']
  with_items:
    - submission
  tags:
    - firewall

- name: start and enable postfix
  ansible.builtin.service: name=postfix state=started enabled=yes
